# Generated by Django 4.1.3 on 2022-12-14 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_customeruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
